<?php 

return [
    'admin'             => 'bullseye',
    'agenda'            => 'book',
    'alert'             => 'exclamation-triangle',
    'arrow-left'        => 'arrow-left',
    'arrow-right'       => 'arrow-right',
    'assign'            => 'arrow-circle-right',
    'bars'              => 'bars',
    'building'          => 'university',
    'bus'               => 'bus',
    'calendar'          => 'calendar-times-o',
    'car'               => 'car',
    'cancel'            => 'ban',
    'change'            => 'retweet',
    'clients'           => 'handshake-o',
    'company'           => 'briefcase',
    'config'            => 'gear',
    'date'              => 'calendar',
    'delete'            => 'trash',
    'download'          => 'download',
    'edit'              => 'pencil',
    'email'             => 'envelope',
    'euro'              => 'eur',
    'excel'             => 'table',
    'exit'              => 'power-off',
    'file'              => 'file-text',
    'form'              => 'check-square-o',
    'framework'         => 'align-justify',
    'graph'             => 'line-chart',
    'hashtag'           => 'hashtag',
    'id'                => 'id-card',
    'info'              => 'info-circle',
    'invoice'           => 'file-text',
    'map'               => 'map-marker',
    'minus'             => 'minus',
    'new'               => 'plus-circle',
    'note'              => 'sticky-note',
    'password'          => 'unlock-alt',
    'percent'           => 'percent',
    'profile'           => 'cog',
    'question'          => 'question-circle',
    'reset'             => 'undo',
    'search'            => 'search',
    'select'            => 'check-square',
    'social'            => 'facebook-square',
    'submit'            => 'share-square-o',
    'success'           => 'thumbs-up',
    'suitcase'          => 'suitcase',
    'table'             => 'table',
    'time'              => 'clock-o',
    'telephone'         => 'phone-square',
    'print'             => 'print',
    'pointer'           => 'hand-pointer-o',
    'upload'            => 'upload',
    'user'              => 'user-circle',
    'users'             => 'users',
    'world'             => 'globe',
    'wrench'            => 'wrench',

    //Specials
    'check'             => 'check-square-o',
    'uncheck'           => 'square-o',

    //Menu
    'add'               => 'plus',
    'agronomics'        => 'pagelines',
    'biocides'          => 'flask',
    'crops'             => 'envira',
    'culturals'         => 'scissors',
    'equipment'         => 'truck',
    'harvests'          => 'recycle',
    'incidents'         => 'exclamation-triangle',
    'irrigations'       => 'cloud-download',
    'list'              => 'list-alt',
    'pests'             => 'bug',
    'plots'             => 'object-ungroup',
    'tools'             => 'wrench',
    'workers'           => 'address-card',

    //Legends 
    'weather'           => 'snowflake-o',
    'tree'              => 'tree',
    'crop-alt'          => 'pagelines',
];